// Product design: source-linked AI & cloud dependency dashboard with a transparent cross-provider stability lens.
import 'dotenv/config';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getStatusSnapshot } from './store.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = path.resolve(__dirname, '..', 'public');
const escapeHtml = (value) => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&quot;').replace(/'/g, '&#39;');
const siteUrl = () => (process.env.SITE_URL || process.env.URL || 'http://localhost:8080').replace(/\/$/, '');
const dateLabel = (value) => new Date(value).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }) + ' UTC';
const durationLabel = (minutes) => minutes === null ? 'Not supplied' : minutes < 60 ? `${minutes} min` : `${(minutes / 60).toFixed(1)} hr`;

function validHttps(value) { try { return value && new URL(value).protocol === 'https:' ? new URL(value).toString() : null; } catch { return null; } }
function optionalSupport() { const paypal = validHttps(process.env.PAYPAL_ME_LINK); const sponsor = validHttps(process.env.SPONSOR_URL); const label = String(process.env.SPONSOR_LABEL || 'Sponsor').trim(); if (!paypal && !sponsor) return ''; return `<aside class="support"><p class="eyebrow">Optional support</p>${sponsor ? `<p><a href="${escapeHtml(sponsor)}" rel="sponsored noopener noreferrer">${escapeHtml(label)} ↗</a></p>` : ''}${paypal ? `<p><a href="${escapeHtml(paypal)}" rel="sponsored noopener noreferrer">Support this independent tracker ↗</a></p>` : ''}<p class="meta">Support links never affect scores, source selection or incident interpretation.</p></aside>`; }

function page({ title, description, body, canonical }) {
  const base = siteUrl();
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${escapeHtml(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${escapeHtml(canonical || base)}"><title>${escapeHtml(title)}</title><style>
  :root{--ink:#111c26;--muted:#60707c;--paper:#f3f2ec;--panel:#fffdfa;--line:#d8ded9;--nav:#102d3a;--aqua:#16816f;--sun:#f2c94c;--steady:#4e846d;--watch:#9e6e20;--elevated:#bd603d;--critical:#713d5d}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Georgia,'Times New Roman',serif;line-height:1.55}a{color:var(--aqua)}header{background:var(--nav);color:#f4f6ef;border-bottom:5px solid var(--sun);padding:1.1rem max(1.2rem,calc((100vw - 78rem)/2));display:flex;justify-content:space-between;align-items:center;gap:1rem}header a{color:inherit;text-decoration:none;font:700 .78rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;text-transform:uppercase}.nav{display:flex;gap:1rem;flex-wrap:wrap}.nav a{opacity:.84}.nav a:hover{opacity:1}main{width:min(78rem,calc(100% - 2.4rem));margin:auto;padding:3.5rem 0 5rem}.eyebrow{font:700 .74rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;text-transform:uppercase;color:var(--aqua)}h1{font-size:clamp(2.9rem,7vw,5.8rem);line-height:.9;letter-spacing:-.065em;max-width:14ch;margin:.55rem 0 1rem}.lede{font-size:1.18rem;max-width:67ch}.meta{font:500 .78rem/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}.top{display:grid;grid-template-columns:1.5fr .8fr;gap:2rem;align-items:end}.notice,.support{padding:1.15rem;border:1px solid var(--line);background:#edf4e8}.posture{font-size:1.6rem;font-weight:700;margin:.4rem 0}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1.25rem;margin-top:2.5rem}.card{background:var(--panel);border:1px solid var(--line);padding:1.3rem}.provider{display:flex;justify-content:space-between;gap:1rem;align-items:baseline}.provider h2{margin:0;font-size:1.55rem}.score{font:700 2.5rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:-.08em}.score small{font-size:.75rem;letter-spacing:0}.badge{display:inline-block;padding:.32rem .58rem;color:white;font:700 .68rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.06em;text-transform:uppercase}.steady{background:var(--steady)}.watch{background:var(--watch)}.elevated{background:var(--elevated)}.critical{background:var(--critical)}.row{padding:.82rem 0;border-top:1px solid var(--line)}.row strong{display:block}.incident{padding:.72rem 0;border-top:1px solid var(--line)}.incident:first-child{border-top:0}.support{margin-top:2.5rem;background:#fff6da}footer{padding:2rem max(1.2rem,calc((100vw - 78rem)/2));border-top:1px solid var(--line);color:var(--muted);font-size:.9rem}@media(max-width:860px){.top,.cards{grid-template-columns:1fr}main{padding-top:2.3rem}h1{font-size:3.5rem}}
  </style></head><body><header><a href="${escapeHtml(base)}/">Dependency Lens</a><nav class="nav"><a href="${escapeHtml(base)}/methodology/">Methodology</a><a href="https://www.githubstatus.com" rel="noopener noreferrer">Official sources ↗</a></nav></header><main>${body}</main><footer>Independent, source-linked interpretation of public status information. Not affiliated with, endorsed by, or an official status product of any tracked provider.</footer></body></html>`;
}

function incidentList(incidents) { if (!incidents.length) return '<p class="meta">No recent official incident entries were returned.</p>'; return `<div>${incidents.slice(0, 3).map((incident) => `<section class="incident"><strong>${escapeHtml(incident.name)}</strong><span class="meta">${escapeHtml(incident.impact)} impact · ${escapeHtml(incident.status)}${incident.durationMinutes === null ? '' : ` · ${escapeHtml(durationLabel(incident.durationMinutes))}`}</span></section>`).join('')}</div>`; }
function providerCard(provider) { return `<article class="card"><div class="provider"><h2>${escapeHtml(provider.name)}</h2><a class="meta" href="${escapeHtml(provider.officialUrl)}" rel="noopener noreferrer">Source ↗</a></div><p class="meta">${escapeHtml(provider.focus)}</p><div class="score">${escapeHtml(provider.score)}<small>/100</small></div><p><span class="badge ${escapeHtml(provider.current.tone)}">${escapeHtml(provider.current.label)}</span></p><p>${escapeHtml(provider.current.officialDescription)}</p><section class="row"><strong>Score deductions</strong><span class="meta">Current ${provider.deductions.current} · Unresolved ${provider.deductions.unresolved} · Recent history ${provider.deductions.recentHistory}</span></section><section class="row"><strong>Dependency indicators</strong><span class="meta">${provider.affectedComponents.length ? escapeHtml(provider.affectedComponents.map((component) => `${component.name}: ${component.status}`).join(' · ')) : 'No non-operational official components reported.'}</span></section><section class="row"><strong>Recent official incidents</strong>${incidentList(provider.unresolvedIncidents.length ? provider.unresolvedIncidents : provider.recentIncidents)}</section><p class="meta">Observed ${provider.componentsObserved} official components${provider.averageResolutionMinutes === null ? '' : ` · mean resolved duration in returned history: ${durationLabel(provider.averageResolutionMinutes)}`}</p></article>`; }

function index(snapshot) { const body = `<div class="top"><section><p class="eyebrow">Cross-provider operational context</p><h1>Know your dependency posture.</h1><p class="lede">An independent lens for teams that rely on multiple AI and developer platforms. We normalize current official service signals and recent official incidents into a transparent, source-linked stability view — so a single provider page is not your only operational context.</p><p class="meta">Collected ${escapeHtml(dateLabel(snapshot.timestamp))} · ${snapshot.providers.length} official sources</p></section><aside class="notice"><p class="eyebrow">Portfolio posture</p><p class="posture">${escapeHtml(snapshot.portfolio.label)}</p><p>${escapeHtml(snapshot.portfolio.rationale)}</p><p class="meta">This is an independent interpretation, not an SLA, uptime claim or prediction.</p></aside></div><section class="cards">${snapshot.providers.map(providerCard).join('')}</section>${optionalSupport()}`; return page({ title: 'AI & Cloud Status Tracker | Dependency Stability Lens', description: 'Source-linked AI and cloud dependency tracker with transparent stability scores and official incident context.', body }); }
function methodology(snapshot) { const body = `<p class="eyebrow">Methodology & source boundaries</p><h1>Scores you can audit.</h1><p class="lede">The Weekly Stability Score starts at 100. It deducts only documented public status signals: current official component severity, unresolved official incident impact, and resolved incidents initiated in the preceding seven days.</p><h2>Deduction rules</h2><p>Operational components deduct 0. Degraded performance deducts 12. Partial outage deducts 30. Major outage or critical conditions deduct 55. Unresolved official incidents deduct up to 20 and recent resolved incidents deduct up to 25. The score is bounded at 0; it does not estimate private customer experience.</p><h2>Dependency posture</h2><p>Diversified posture means no tracked provider is currently non-operational or below 88. Single-provider watch means one provider is below that threshold or reports an issue. Cross-provider exposure means two or more providers meet that condition.</p><h2>Sources and attribution</h2><p>The tracker requests machine-readable, public status endpoints from OpenAI, Claude and GitHub. Each card links to the provider's official status page. Provider availability descriptions remain the providers’ own status information; our score and posture are independent interpretations. This product is not affiliated with, endorsed by or an official product of any provider.</p><h2>Limits</h2><p>Status pages can be delayed, aggregate availability across services or tiers, omit customer-specific conditions, or revise incident records. Use the official source for operational decisions, alerts and vendor support.</p><p class="meta">Latest collection: ${escapeHtml(dateLabel(snapshot.timestamp))}</p>${optionalSupport()}<p><a href="${escapeHtml(siteUrl())}/">← Back to Dependency Lens</a></p>`; return page({ title: 'Methodology | Dependency Stability Lens', description: 'Transparent scoring rules, source links, attribution and limits for the AI and cloud status tracker.', body, canonical: `${siteUrl()}/methodology/` }); }

export async function buildSite({ snapshot, outputDir = OUTPUT_DIR } = {}) { const data = snapshot || await getStatusSnapshot(); if (data?.kind !== 'dependency-stability-lens') throw new Error('Dependency Stability Lens snapshot is required. Run the collector first.'); const base = siteUrl(); await rm(outputDir, { recursive: true, force: true }); await mkdir(path.join(outputDir, 'methodology'), { recursive: true }); await Promise.all([writeFile(path.join(outputDir, 'index.html'), index(data), 'utf8'), writeFile(path.join(outputDir, 'methodology', 'index.html'), methodology(data), 'utf8'), writeFile(path.join(outputDir, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`, 'utf8'), writeFile(path.join(outputDir, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>${base}/</loc><lastmod>${data.timestamp}</lastmod></url>\n  <url><loc>${base}/methodology/</loc><lastmod>${data.timestamp}</lastmod></url>\n</urlset>\n`, 'utf8'), writeFile(path.join(outputDir, '.nojekyll'), '', 'utf8')]); return { outputDir, pages: 2, timestamp: data.timestamp }; }

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) buildSite().then((result) => console.info(JSON.stringify({ status: 'built', ...result }))).catch((error) => { console.error(error); process.exit(1); });
